"""make courses global

Revision ID: 4b016bf285d3
Revises: a7e31b9c04d2
Create Date: 2026-07-10 17:41:02.776585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b016bf285d3'
down_revision: Union[str, None] = 'a7e31b9c04d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_courses',
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('madrasa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['madrasa_id'], ['madaris.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'course_id', name='uq_class_course')
    )
    op.create_index(op.f('ix_class_courses_class_id'), 'class_courses', ['class_id'], unique=False)
    op.create_index(op.f('ix_class_courses_course_id'), 'class_courses', ['course_id'], unique=False)
    op.create_index(op.f('ix_class_courses_madrasa_id'), 'class_courses', ['madrasa_id'], unique=False)
    op.drop_constraint('courses_class_id_fkey', 'courses', type_='foreignkey')
    op.drop_column('courses', 'class_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('class_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('courses_class_id_fkey', 'courses', 'classes', ['class_id'], ['id'])
    op.drop_index(op.f('ix_class_courses_madrasa_id'), table_name='class_courses')
    op.drop_index(op.f('ix_class_courses_course_id'), table_name='class_courses')
    op.drop_index(op.f('ix_class_courses_class_id'), table_name='class_courses')
    op.drop_table('class_courses')
    # ### end Alembic commands ###
