"""add is_principal_delegate to teacher_profiles

Revision ID: 66eb6a081f25
Revises: f8cf3ec5ccc3
Create Date: 2026-07-21 18:50:33.785508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66eb6a081f25'
down_revision: Union[str, None] = 'f8cf3ec5ccc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_course_madrasa_normalized_name', table_name='courses')
    op.create_index('uq_course_madrasa_normalized_name', 'courses', ['madrasa_id', sa.text('lower(trim(name))')], unique=True)
    op.add_column('exam_types', sa.Column('class_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_exam_types_class_id'), 'exam_types', ['class_id'], unique=False)
    op.create_foreign_key(None, 'exam_types', 'classes', ['class_id'], ['id'])
    op.add_column(
        'teacher_profiles',
        sa.Column('is_principal_delegate', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher_profiles', 'is_principal_delegate')
    op.drop_constraint(None, 'exam_types', type_='foreignkey')
    op.drop_index(op.f('ix_exam_types_class_id'), table_name='exam_types')
    op.drop_column('exam_types', 'class_id')
    op.drop_index('uq_course_madrasa_normalized_name', table_name='courses')
    op.create_index('uq_course_madrasa_normalized_name', 'courses', ['madrasa_id', sa.text('lower(TRIM(BOTH FROM name))')], unique=True)
    # ### end Alembic commands ###
