"""Add max_marks and weightage to Assignment

Revision ID: 9710ceddf791
Revises: 66eb6a081f25
Create Date: 2026-07-21 19:10:33.494519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9710ceddf791'
down_revision: Union[str, None] = '66eb6a081f25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('max_marks', sa.Float(), nullable=True))
    op.add_column('assignments', sa.Column('weightage', sa.Float(), nullable=True))
    op.drop_index('uq_course_madrasa_normalized_name', table_name='courses')
    op.create_index('uq_course_madrasa_normalized_name', 'courses', ['madrasa_id', sa.text('lower(trim(name))')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_course_madrasa_normalized_name', table_name='courses')
    op.create_index('uq_course_madrasa_normalized_name', 'courses', ['madrasa_id', sa.text('lower(TRIM(BOTH FROM name))')], unique=True)
    op.drop_column('assignments', 'weightage')
    op.drop_column('assignments', 'max_marks')
    # ### end Alembic commands ###
