"""Make FormResponse student_id optional

Revision ID: aaeb664a3063
Revises: 7a2f1c9d4e60
Create Date: 2026-07-21 13:56:10.381212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaeb664a3063'
down_revision: Union[str, None] = '7a2f1c9d4e60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('admission_forms_public_token_key', 'admission_forms', type_='unique')
    op.drop_index('ix_admission_forms_public_token', table_name='admission_forms')
    op.create_index(op.f('ix_admission_forms_public_token'), 'admission_forms', ['public_token'], unique=True)
    op.drop_index('uq_course_madrasa_normalized_name', table_name='courses')
    op.create_index('uq_course_madrasa_normalized_name', 'courses', ['madrasa_id', sa.text('lower(trim(name))')], unique=True)
    op.alter_column('form_responses', 'student_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('form_responses', 'student_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('uq_course_madrasa_normalized_name', table_name='courses')
    op.create_index('uq_course_madrasa_normalized_name', 'courses', ['madrasa_id', sa.text('lower(TRIM(BOTH FROM name))')], unique=True)
    op.drop_index(op.f('ix_admission_forms_public_token'), table_name='admission_forms')
    op.create_index('ix_admission_forms_public_token', 'admission_forms', ['public_token'], unique=False)
    op.create_unique_constraint('admission_forms_public_token_key', 'admission_forms', ['public_token'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
