"""Initial schema

Revision ID: d74c9c7a4b64
Revises: 
Create Date: 2026-07-03 21:01:17.594197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd74c9c7a4b64'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('madaris',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('content_language', sa.String(length=8), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_madaris_slug'), 'madaris', ['slug'], unique=True)
    op.create_table('academic_sessions',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('gregorian_start', sa.Date(), nullable=False),
    sa.Column('gregorian_end', sa.Date(), nullable=False),
    sa.Column('hijri_span', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('madrasa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['madrasa_id'], ['madaris.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_sessions_madrasa_id'), 'academic_sessions', ['madrasa_id'], unique=False)
    op.create_table('donors',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('contact', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('madrasa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['madrasa_id'], ['madaris.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donors_madrasa_id'), 'donors', ['madrasa_id'], unique=False)
    op.create_table('grading_schemes',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('bands', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('madrasa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['madrasa_id'], ['madaris.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grading_schemes_madrasa_id'), 'grading_schemes', ['madrasa_id'], unique=False)
    op.create_table('guardians',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('relationship', sa.String(length=80), nullable=False),
    sa.Column('phone_numbers', sa.Text(), nullable=False),
    sa.Column('preferred_language', sa.String(length=8), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('madrasa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['madrasa_id'], ['madaris.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guardians_madrasa_id'), 'guardians', ['madrasa_id'], unique=False)
    op.create_table('holidays',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('madrasa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['madrasa_id'], ['madaris.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holidays_madrasa_id'), 'holidays', ['madrasa_id'], unique=False)
    op.create_table('message_templates',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('madrasa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['madrasa_id'], ['madaris.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_templates_code'), 'message_templates', ['code'], unique=True)
    op.create_index(op.f('ix_message_templates_madrasa_id'), 'message_templates', ['madrasa_id'], unique=False)
    op.create_table('payment_categories',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('madrasa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['madrasa_id'], ['madaris.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_categories_madrasa_id'), 'payment_categories', ['madrasa_id'], unique=False)
    op.create_table('programs',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('madrasa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['madrasa_id'], ['madaris.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programs_madrasa_id'), 'programs', ['madrasa_id'], unique=False)
    op.create_table('resource_categories',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('madrasa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['madrasa_id'], ['madaris.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_categories_madrasa_id'), 'resource_categories', ['madrasa_id'], unique=False)
    op.create_table('users',
    sa.Column('madrasa_id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('principal', 'teacher', 'student', name='userrole'), nullable=False),
    sa.Column('preferred_language', sa.String(length=8), nullable=False),
    sa.Column('status', sa.Enum('invited', 'active', 'disabled', name='userstatus'), nullable=False),
    sa.Column('portal_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['madrasa_id'], ['madaris.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_madrasa_id'), 'users', ['madrasa_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('attendance_corrections',
    sa.Column('attendance_table', sa.String(length=40), nullable=False),
    sa.Column('attendance_id', sa.Uuid(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=False),
    sa.Column('new_value', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('madrasa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['madrasa_id'], ['madaris.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_corrections_madrasa_id'), 'attendance_corrections', ['madrasa_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=160), nullable=False),
    sa.Column('entity_name', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('new_values', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('action_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('madrasa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['madrasa_id'], ['madaris.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_name'), 'audit_logs', ['entity_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_madrasa_id'), 'audit_logs', ['madrasa_id'], unique=False)
    op.create_table('classes',
    sa.Column('program_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('default_portal_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('madrasa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['madrasa_id'], ['madaris.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_madrasa_id'), 'classes', ['madrasa_id'], unique=False)
    op.create_table('donations',
    sa.Column('donor_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('donation_date', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('recorded_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('madrasa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['payment_categories.id'], ),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ),
    sa.ForeignKeyConstraint(['madrasa_id'], ['madaris.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donations_donor_id'), 'donations', ['donor_id'], unique=False)
    op.create_index(op.f('ix_donations_madrasa_id'), 'donations', ['madrasa_id'], unique=False)
    op.create_table('file_objects',
    sa.Column('object_key', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=80), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('scope', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('madrasa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['madrasa_id'], ['madaris.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_objects_madrasa_id'), 'file_objects', ['madrasa_id'], unique=False)
    op.create_index(op.f('ix_file_objects_object_key'), 'file_objects', ['object_key'], unique=True)
    op.create_table('forms',
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('fields_definition', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('visibility_scope', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('open_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('allow_multiple', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('madrasa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['madrasa_id'], ['madaris.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forms_madrasa_id'), 'forms', ['madrasa_id'], unique=False)
    op.create_table('leaves',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('madrasa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['madrasa_id'], ['madaris.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaves_madrasa_id'), 'leaves', ['madrasa_id'], unique=False)
    op.create_index(op.f('ix_leaves_user_id'), 'leaves', ['user_id'], unique=False)
    op.create_table('message_logs',
    sa.Column('template_code', sa.String(length=80), nullable=False),
    sa.Column('recipient_number', sa.String(length=32), nullable=False),
    sa.Column('recipient_type', sa.String(length=32), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_by_id', sa.Uuid(), nullable=False),
    sa.Column('content_sent', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('madrasa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['madrasa_id'], ['madaris.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sent_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_logs_madrasa_id'), 'message_logs', ['madrasa_id'], unique=False)
    op.create_table('resources',
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('file_key', sa.String(length=255), nullable=False),
    sa.Column('video_url', sa.String(length=255), nullable=False),
    sa.Column('visibility_scope', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('madrasa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['resource_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['madrasa_id'], ['madaris.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_category_id'), 'resources', ['category_id'], unique=False)
    op.create_index(op.f('ix_resources_madrasa_id'), 'resources', ['madrasa_id'], unique=False)
    op.create_table('student_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('admission_number', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('madrasa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['madrasa_id'], ['madaris.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admission_number')
    )
    op.create_index(op.f('ix_student_profiles_madrasa_id'), 'student_profiles', ['madrasa_id'], unique=False)
    op.create_table('teacher_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('employee_code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('whatsapp_number', sa.String(length=32), nullable=False),
    sa.Column('qualifications', sa.Text(), nullable=True),
    sa.Column('join_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('madrasa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['madrasa_id'], ['madaris.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_code')
    )
    op.create_index(op.f('ix_teacher_profiles_madrasa_id'), 'teacher_profiles', ['madrasa_id'], unique=False)
    op.create_table('user_permissions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('permission_code', sa.String(length=120), nullable=False),
    sa.Column('granted_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_permissions_permission_code'), 'user_permissions', ['permission_code'], unique=False)
    op.create_index(op.f('ix_user_permissions_user_id'), 'user_permissions', ['user_id'], unique=False)
    op.create_table('courses',
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('madrasa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['madrasa_id'], ['madaris.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_madrasa_id'), 'courses', ['madrasa_id'], unique=False)
    op.create_table('form_responses',
    sa.Column('form_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('submitted_by_id', sa.Uuid(), nullable=False),
    sa.Column('response_data', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('madrasa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.ForeignKeyConstraint(['madrasa_id'], ['madaris.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_responses_form_id'), 'form_responses', ['form_id'], unique=False)
    op.create_index(op.f('ix_form_responses_madrasa_id'), 'form_responses', ['madrasa_id'], unique=False)
    op.create_index(op.f('ix_form_responses_student_id'), 'form_responses', ['student_id'], unique=False)
    op.create_table('payments',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('recorded_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('madrasa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['payment_categories.id'], ),
    sa.ForeignKeyConstraint(['madrasa_id'], ['madaris.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_madrasa_id'), 'payments', ['madrasa_id'], unique=False)
    op.create_index(op.f('ix_payments_student_id'), 'payments', ['student_id'], unique=False)
    op.create_table('salary_payments',
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('period_covered', sa.String(length=80), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('recorded_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('madrasa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['madrasa_id'], ['madaris.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_payments_madrasa_id'), 'salary_payments', ['madrasa_id'], unique=False)
    op.create_index(op.f('ix_salary_payments_teacher_id'), 'salary_payments', ['teacher_id'], unique=False)
    op.create_table('salary_records',
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('madrasa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['madrasa_id'], ['madaris.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_records_madrasa_id'), 'salary_records', ['madrasa_id'], unique=False)
    op.create_index(op.f('ix_salary_records_teacher_id'), 'salary_records', ['teacher_id'], unique=True)
    op.create_table('sections',
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('madrasa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['madrasa_id'], ['madaris.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sections_madrasa_id'), 'sections', ['madrasa_id'], unique=False)
    op.create_table('student_attendance',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('present', 'absent', 'leave', name='attendancestatus'), nullable=False),
    sa.Column('marked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('marked_by_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('synced_late', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('madrasa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['madrasa_id'], ['madaris.id'], ),
    sa.ForeignKeyConstraint(['marked_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['academic_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_student_attendance_attendance_date'), 'student_attendance', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_student_attendance_madrasa_id'), 'student_attendance', ['madrasa_id'], unique=False)
    op.create_index(op.f('ix_student_attendance_session_id'), 'student_attendance', ['session_id'], unique=False)
    op.create_index(op.f('ix_student_attendance_student_id'), 'student_attendance', ['student_id'], unique=False)
    op.create_table('student_guardians',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('guardian_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardians.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_attendance',
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('present', 'absent', 'leave', name='attendancestatus'), nullable=False),
    sa.Column('check_in', sa.Time(), nullable=True),
    sa.Column('check_out', sa.Time(), nullable=True),
    sa.Column('marked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('marked_by_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('synced_late', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('madrasa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['madrasa_id'], ['madaris.id'], ),
    sa.ForeignKeyConstraint(['marked_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['academic_sessions.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_teacher_attendance_attendance_date'), 'teacher_attendance', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_teacher_attendance_madrasa_id'), 'teacher_attendance', ['madrasa_id'], unique=False)
    op.create_index(op.f('ix_teacher_attendance_session_id'), 'teacher_attendance', ['session_id'], unique=False)
    op.create_index(op.f('ix_teacher_attendance_teacher_id'), 'teacher_attendance', ['teacher_id'], unique=False)
    op.create_table('assignments',
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('attachment_key', sa.String(length=255), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('madrasa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['teacher_profiles.id'], ),
    sa.ForeignKeyConstraint(['madrasa_id'], ['madaris.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_class_id'), 'assignments', ['class_id'], unique=False)
    op.create_index(op.f('ix_assignments_course_id'), 'assignments', ['course_id'], unique=False)
    op.create_index(op.f('ix_assignments_madrasa_id'), 'assignments', ['madrasa_id'], unique=False)
    op.create_table('enrollments',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('program_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('madrasa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['madrasa_id'], ['madaris.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['academic_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrollments_madrasa_id'), 'enrollments', ['madrasa_id'], unique=False)
    op.create_index(op.f('ix_enrollments_session_id'), 'enrollments', ['session_id'], unique=False)
    op.create_index(op.f('ix_enrollments_student_id'), 'enrollments', ['student_id'], unique=False)
    op.create_table('exam_types',
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('weightage', sa.Float(), nullable=False),
    sa.Column('grading_scheme_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('madrasa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['grading_scheme_id'], ['grading_schemes.id'], ),
    sa.ForeignKeyConstraint(['madrasa_id'], ['madaris.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_types_course_id'), 'exam_types', ['course_id'], unique=False)
    op.create_index(op.f('ix_exam_types_madrasa_id'), 'exam_types', ['madrasa_id'], unique=False)
    op.create_table('teacher_assignments',
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('madrasa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['madrasa_id'], ['madaris.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['academic_sessions.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_assignments_madrasa_id'), 'teacher_assignments', ['madrasa_id'], unique=False)
    op.create_index(op.f('ix_teacher_assignments_session_id'), 'teacher_assignments', ['session_id'], unique=False)
    op.create_index(op.f('ix_teacher_assignments_teacher_id'), 'teacher_assignments', ['teacher_id'], unique=False)
    op.create_table('timetable_slots',
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=20), nullable=False),
    sa.Column('end_time', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('madrasa_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['madrasa_id'], ['madaris.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_slots_class_id'), 'timetable_slots', ['class_id'], unique=False)
    op.create_index(op.f('ix_timetable_slots_course_id'), 'timetable_slots', ['course_id'], unique=False)
    op.create_index(op.f('ix_timetable_slots_madrasa_id'), 'timetable_slots', ['madrasa_id'], unique=False)
    op.create_index(op.f('ix_timetable_slots_section_id'), 'timetable_slots', ['section_id'], unique=False)
    op.create_index(op.f('ix_timetable_slots_teacher_id'), 'timetable_slots', ['teacher_id'], unique=False)
    op.create_table('marks',
    sa.Column('exam_type_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('entered_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entered_by_id'], ['teacher_profiles.id'], ),
    sa.ForeignKeyConstraint(['exam_type_id'], ['exam_types.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marks_exam_type_id'), 'marks', ['exam_type_id'], unique=False)
    op.create_index(op.f('ix_marks_student_id'), 'marks', ['student_id'], unique=False)
    op.create_table('submissions',
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_key', sa.String(length=255), nullable=False),
    sa.Column('mark', sa.Float(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_assignment_id'), 'submissions', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_submissions_student_id'), 'submissions', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_student_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_assignment_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_marks_student_id'), table_name='marks')
    op.drop_index(op.f('ix_marks_exam_type_id'), table_name='marks')
    op.drop_table('marks')
    op.drop_index(op.f('ix_timetable_slots_teacher_id'), table_name='timetable_slots')
    op.drop_index(op.f('ix_timetable_slots_section_id'), table_name='timetable_slots')
    op.drop_index(op.f('ix_timetable_slots_madrasa_id'), table_name='timetable_slots')
    op.drop_index(op.f('ix_timetable_slots_course_id'), table_name='timetable_slots')
    op.drop_index(op.f('ix_timetable_slots_class_id'), table_name='timetable_slots')
    op.drop_table('timetable_slots')
    op.drop_index(op.f('ix_teacher_assignments_teacher_id'), table_name='teacher_assignments')
    op.drop_index(op.f('ix_teacher_assignments_session_id'), table_name='teacher_assignments')
    op.drop_index(op.f('ix_teacher_assignments_madrasa_id'), table_name='teacher_assignments')
    op.drop_table('teacher_assignments')
    op.drop_index(op.f('ix_exam_types_madrasa_id'), table_name='exam_types')
    op.drop_index(op.f('ix_exam_types_course_id'), table_name='exam_types')
    op.drop_table('exam_types')
    op.drop_index(op.f('ix_enrollments_student_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_session_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_madrasa_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_assignments_madrasa_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_course_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_class_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_teacher_attendance_teacher_id'), table_name='teacher_attendance')
    op.drop_index(op.f('ix_teacher_attendance_session_id'), table_name='teacher_attendance')
    op.drop_index(op.f('ix_teacher_attendance_madrasa_id'), table_name='teacher_attendance')
    op.drop_index(op.f('ix_teacher_attendance_attendance_date'), table_name='teacher_attendance')
    op.drop_table('teacher_attendance')
    op.drop_table('student_guardians')
    op.drop_index(op.f('ix_student_attendance_student_id'), table_name='student_attendance')
    op.drop_index(op.f('ix_student_attendance_session_id'), table_name='student_attendance')
    op.drop_index(op.f('ix_student_attendance_madrasa_id'), table_name='student_attendance')
    op.drop_index(op.f('ix_student_attendance_attendance_date'), table_name='student_attendance')
    op.drop_table('student_attendance')
    op.drop_index(op.f('ix_sections_madrasa_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_salary_records_teacher_id'), table_name='salary_records')
    op.drop_index(op.f('ix_salary_records_madrasa_id'), table_name='salary_records')
    op.drop_table('salary_records')
    op.drop_index(op.f('ix_salary_payments_teacher_id'), table_name='salary_payments')
    op.drop_index(op.f('ix_salary_payments_madrasa_id'), table_name='salary_payments')
    op.drop_table('salary_payments')
    op.drop_index(op.f('ix_payments_student_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_madrasa_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_form_responses_student_id'), table_name='form_responses')
    op.drop_index(op.f('ix_form_responses_madrasa_id'), table_name='form_responses')
    op.drop_index(op.f('ix_form_responses_form_id'), table_name='form_responses')
    op.drop_table('form_responses')
    op.drop_index(op.f('ix_courses_madrasa_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_user_permissions_user_id'), table_name='user_permissions')
    op.drop_index(op.f('ix_user_permissions_permission_code'), table_name='user_permissions')
    op.drop_table('user_permissions')
    op.drop_index(op.f('ix_teacher_profiles_madrasa_id'), table_name='teacher_profiles')
    op.drop_table('teacher_profiles')
    op.drop_index(op.f('ix_student_profiles_madrasa_id'), table_name='student_profiles')
    op.drop_table('student_profiles')
    op.drop_index(op.f('ix_resources_madrasa_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_category_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_message_logs_madrasa_id'), table_name='message_logs')
    op.drop_table('message_logs')
    op.drop_index(op.f('ix_leaves_user_id'), table_name='leaves')
    op.drop_index(op.f('ix_leaves_madrasa_id'), table_name='leaves')
    op.drop_table('leaves')
    op.drop_index(op.f('ix_forms_madrasa_id'), table_name='forms')
    op.drop_table('forms')
    op.drop_index(op.f('ix_file_objects_object_key'), table_name='file_objects')
    op.drop_index(op.f('ix_file_objects_madrasa_id'), table_name='file_objects')
    op.drop_table('file_objects')
    op.drop_index(op.f('ix_donations_madrasa_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_donor_id'), table_name='donations')
    op.drop_table('donations')
    op.drop_index(op.f('ix_classes_madrasa_id'), table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('ix_audit_logs_madrasa_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_attendance_corrections_madrasa_id'), table_name='attendance_corrections')
    op.drop_table('attendance_corrections')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_madrasa_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_resource_categories_madrasa_id'), table_name='resource_categories')
    op.drop_table('resource_categories')
    op.drop_index(op.f('ix_programs_madrasa_id'), table_name='programs')
    op.drop_table('programs')
    op.drop_index(op.f('ix_payment_categories_madrasa_id'), table_name='payment_categories')
    op.drop_table('payment_categories')
    op.drop_index(op.f('ix_message_templates_madrasa_id'), table_name='message_templates')
    op.drop_index(op.f('ix_message_templates_code'), table_name='message_templates')
    op.drop_table('message_templates')
    op.drop_index(op.f('ix_holidays_madrasa_id'), table_name='holidays')
    op.drop_table('holidays')
    op.drop_index(op.f('ix_guardians_madrasa_id'), table_name='guardians')
    op.drop_table('guardians')
    op.drop_index(op.f('ix_grading_schemes_madrasa_id'), table_name='grading_schemes')
    op.drop_table('grading_schemes')
    op.drop_index(op.f('ix_donors_madrasa_id'), table_name='donors')
    op.drop_table('donors')
    op.drop_index(op.f('ix_academic_sessions_madrasa_id'), table_name='academic_sessions')
    op.drop_table('academic_sessions')
    op.drop_index(op.f('ix_madaris_slug'), table_name='madaris')
    op.drop_table('madaris')
    # ### end Alembic commands ###
