"""scope_employee_code_to_tenant

Revision ID: e1fe6e517f95
Revises: iss3_035_drop_daily_report_slug
Create Date: 2026-08-29 01:51:49.599393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1fe6e517f95'
down_revision: Union[str, None] = 'iss3_035_drop_daily_report_slug'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('teacher_profiles_employee_code_key', 'teacher_profiles', type_='unique')
    op.create_unique_constraint('uq_teacher_employee_code_tenant', 'teacher_profiles', ['madrasa_id', 'employee_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_teacher_employee_code_tenant', 'teacher_profiles', type_='unique')
    op.create_unique_constraint('teacher_profiles_employee_code_key', 'teacher_profiles', ['employee_code'])
    # ### end Alembic commands ###
