/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademicsRouteImport } from './routes/academics'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as FormsRouteImport } from './routes/forms'
import { Route as HolidaysRouteImport } from './routes/holidays'
import { Route as LeaveRouteImport } from './routes/leave'
import { Route as MeRouteImport } from './routes/me'
import { Route as MoreRouteImport } from './routes/more'
import { Route as MyProfileRouteImport } from './routes/my-profile'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as AdmissionTokenRouteImport } from './routes/admission.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsRoute = AcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRoute = FormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const HolidaysRoute = HolidaysRouteImport.update({
  id: '/holidays',
  path: '/holidays',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveRoute = LeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProfileRoute = MyProfileRouteImport.update({
  id: '/my-profile',
  path: '/my-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionTokenRoute = AdmissionTokenRouteImport.update({
  id: '/admission/$token',
  path: '/admission/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/announcements': typeof AnnouncementsRoute
  '/assignments': typeof AssignmentsRoute
  '/attendance': typeof AttendanceRoute
  '/blog': typeof BlogRoute
  '/dashboard': typeof DashboardRoute
  '/finance': typeof FinanceRoute
  '/forms': typeof FormsRoute
  '/holidays': typeof HolidaysRoute
  '/leave': typeof LeaveRoute
  '/me': typeof MeRoute
  '/more': typeof MoreRoute
  '/my-profile': typeof MyProfileRoute
  '/people': typeof PeopleRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/resources': typeof ResourcesRoute
  '/results': typeof ResultsRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRoute
  '/timetable': typeof TimetableRoute
  '/admission/$token': typeof AdmissionTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/announcements': typeof AnnouncementsRoute
  '/assignments': typeof AssignmentsRoute
  '/attendance': typeof AttendanceRoute
  '/blog': typeof BlogRoute
  '/dashboard': typeof DashboardRoute
  '/finance': typeof FinanceRoute
  '/forms': typeof FormsRoute
  '/holidays': typeof HolidaysRoute
  '/leave': typeof LeaveRoute
  '/me': typeof MeRoute
  '/more': typeof MoreRoute
  '/my-profile': typeof MyProfileRoute
  '/people': typeof PeopleRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/resources': typeof ResourcesRoute
  '/results': typeof ResultsRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRoute
  '/timetable': typeof TimetableRoute
  '/admission/$token': typeof AdmissionTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/announcements': typeof AnnouncementsRoute
  '/assignments': typeof AssignmentsRoute
  '/attendance': typeof AttendanceRoute
  '/blog': typeof BlogRoute
  '/dashboard': typeof DashboardRoute
  '/finance': typeof FinanceRoute
  '/forms': typeof FormsRoute
  '/holidays': typeof HolidaysRoute
  '/leave': typeof LeaveRoute
  '/me': typeof MeRoute
  '/more': typeof MoreRoute
  '/my-profile': typeof MyProfileRoute
  '/people': typeof PeopleRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/resources': typeof ResourcesRoute
  '/results': typeof ResultsRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRoute
  '/timetable': typeof TimetableRoute
  '/admission/$token': typeof AdmissionTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academics'
    | '/admissions'
    | '/announcements'
    | '/assignments'
    | '/attendance'
    | '/blog'
    | '/dashboard'
    | '/finance'
    | '/forms'
    | '/holidays'
    | '/leave'
    | '/me'
    | '/more'
    | '/my-profile'
    | '/people'
    | '/profile'
    | '/reports'
    | '/resources'
    | '/results'
    | '/set-password'
    | '/settings'
    | '/timetable'
    | '/admission/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academics'
    | '/admissions'
    | '/announcements'
    | '/assignments'
    | '/attendance'
    | '/blog'
    | '/dashboard'
    | '/finance'
    | '/forms'
    | '/holidays'
    | '/leave'
    | '/me'
    | '/more'
    | '/my-profile'
    | '/people'
    | '/profile'
    | '/reports'
    | '/resources'
    | '/results'
    | '/set-password'
    | '/settings'
    | '/timetable'
    | '/admission/$token'
  id:
    | '__root__'
    | '/'
    | '/academics'
    | '/admissions'
    | '/announcements'
    | '/assignments'
    | '/attendance'
    | '/blog'
    | '/dashboard'
    | '/finance'
    | '/forms'
    | '/holidays'
    | '/leave'
    | '/me'
    | '/more'
    | '/my-profile'
    | '/people'
    | '/profile'
    | '/reports'
    | '/resources'
    | '/results'
    | '/set-password'
    | '/settings'
    | '/timetable'
    | '/admission/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademicsRoute: typeof AcademicsRoute
  AdmissionsRoute: typeof AdmissionsRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  AssignmentsRoute: typeof AssignmentsRoute
  AttendanceRoute: typeof AttendanceRoute
  BlogRoute: typeof BlogRoute
  DashboardRoute: typeof DashboardRoute
  FinanceRoute: typeof FinanceRoute
  FormsRoute: typeof FormsRoute
  HolidaysRoute: typeof HolidaysRoute
  LeaveRoute: typeof LeaveRoute
  MeRoute: typeof MeRoute
  MoreRoute: typeof MoreRoute
  MyProfileRoute: typeof MyProfileRoute
  PeopleRoute: typeof PeopleRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  ResourcesRoute: typeof ResourcesRoute
  ResultsRoute: typeof ResultsRoute
  SetPasswordRoute: typeof SetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  TimetableRoute: typeof TimetableRoute
  AdmissionTokenRoute: typeof AdmissionTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics': {
      id: '/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holidays': {
      id: '/holidays'
      path: '/holidays'
      fullPath: '/holidays'
      preLoaderRoute: typeof HolidaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave': {
      id: '/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof LeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-profile': {
      id: '/my-profile'
      path: '/my-profile'
      fullPath: '/my-profile'
      preLoaderRoute: typeof MyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admission/$token': {
      id: '/admission/$token'
      path: '/admission/$token'
      fullPath: '/admission/$token'
      preLoaderRoute: typeof AdmissionTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademicsRoute: AcademicsRoute,
  AdmissionsRoute: AdmissionsRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  AssignmentsRoute: AssignmentsRoute,
  AttendanceRoute: AttendanceRoute,
  BlogRoute: BlogRoute,
  DashboardRoute: DashboardRoute,
  FinanceRoute: FinanceRoute,
  FormsRoute: FormsRoute,
  HolidaysRoute: HolidaysRoute,
  LeaveRoute: LeaveRoute,
  MeRoute: MeRoute,
  MoreRoute: MoreRoute,
  MyProfileRoute: MyProfileRoute,
  PeopleRoute: PeopleRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  ResourcesRoute: ResourcesRoute,
  ResultsRoute: ResultsRoute,
  SetPasswordRoute: SetPasswordRoute,
  SettingsRoute: SettingsRoute,
  TimetableRoute: TimetableRoute,
  AdmissionTokenRoute: AdmissionTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
